  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Preparar etapa de pruebas
        run: echo "Etapa de pruebas preparada para B3"

  package:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Preparar etapa de empaquetado
        run: echo "Etapa de empaquetado preparada para B4"

  security:
    needs: package
    runs-on: ubuntu-latest

    steps:
      - name: Preparar etapa de seguridad
        run: echo "Etapa de seguridad preparada para B5"

  smoke:
    needs: security
    runs-on: ubuntu-latest

    steps:
      - name: Preparar pruebas smoke
        run: echo "Etapa smoke preparada para B6"

  deploy-prod:
    needs: smoke
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Preparar despliegue
        run: echo "Etapa de despliegue preparada para B7"